// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRwRMGrAmZw6-_-vtAQupUetnIC_hZYfc',
    appId: '1:204363498820:web:7785143ca3ba41c961c311',
    messagingSenderId: '204363498820',
    projectId: 'smart-expense-manager-f4125',
    authDomain: 'smart-expense-manager-f4125.firebaseapp.com',
    storageBucket: 'smart-expense-manager-f4125.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0jStGcJgsd9Gi9tUUP1KSa__bdvyjn9k',
    appId: '1:204363498820:android:2f51ec784d84bad461c311',
    messagingSenderId: '204363498820',
    projectId: 'smart-expense-manager-f4125',
    storageBucket: 'smart-expense-manager-f4125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtDCVaVsimtbwphtyHMcLysX3zXOwnEWw',
    appId: '1:204363498820:ios:f59733a92925f3b561c311',
    messagingSenderId: '204363498820',
    projectId: 'smart-expense-manager-f4125',
    storageBucket: 'smart-expense-manager-f4125.firebasestorage.app',
    iosBundleId: 'com.amezkhan.smartexpensemanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtDCVaVsimtbwphtyHMcLysX3zXOwnEWw',
    appId: '1:204363498820:ios:49c9c8ee2f5217c561c311',
    messagingSenderId: '204363498820',
    projectId: 'smart-expense-manager-f4125',
    storageBucket: 'smart-expense-manager-f4125.firebasestorage.app',
    iosBundleId: 'com.amezkhan.smartexpensemanager.smartExpenseManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRwRMGrAmZw6-_-vtAQupUetnIC_hZYfc',
    appId: '1:204363498820:web:8abda33f039b34fb61c311',
    messagingSenderId: '204363498820',
    projectId: 'smart-expense-manager-f4125',
    authDomain: 'smart-expense-manager-f4125.firebaseapp.com',
    storageBucket: 'smart-expense-manager-f4125.firebasestorage.app',
  );
}
